### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by wyhmichael** [Arylo/ftconfig#1]
Recently I tried this package with typescript and node 12 on windows 10, and got some overloading error about encoding type, is this project still being maintained actively to take issue reports?

**Comment by Arylo** [comment]
Thanks for your reminding. I'll check this issue soon.

**Comment by wyhmichael** [comment]
Thanks @Arylo , to be more specific about reproduce step : 

* update "@types/node" and "typescript" to latest version 
* check line 47 in lib/index.ts, encoding type is not compatible any more
`    const data = fs.readFileSync(options.path, { encoding: options.encoding });
`

I also did a fork with some change that seems to fix this issue: 
https://github.com/Arylo/ftconfig/compare/master...wyhmichael:master

I'm not sure if you take PR from others so I didn't send one

**Comment by Arylo** [comment]
I'm sorry to forget the issue,  and it would fixed by cfc67501a9df38e9660d155ed2713114a413d50f
